name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: agoose77/cookbook-actions/.github/workflows/build-book.yaml@feat/clinder
    with:
      execute_on_binderhub: true
  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main

  link-check:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
